### ISSUE TITLE
Inspect previous works.

### ISSUE THREAD

**Issue by learnitdeep** [EVlock/Blockgrid#1]
- P2P energy trade paper
- Ethereum security paper
- IoT security paper
- P2P energy trade security paper
- Blockchain - IoT paper
- TrustZone paper

Summarize on Wiki.

**Comment by learnitdeep** [comment]
I'm working on searching Energy trade papers

**Comment by harrydrippin** [comment]
I'm now summarizing [Smart-Grid Security Issues](https://www.researchgate.net/publication/224110557_Smart-Grid_Security_Issues?enrichId=rgreq-41d00f946921e9be1ca839b1f3a2d75a-XXX&enrichSource=Y292ZXJQYWdlOzIyNDExMDU1NztBUzoxMDQxMjM3OTgxMzA3MDhAMTQwMTgzNjQ1Njk1Nw%3D%3D&el=1_x_2&_esc=publicationCoverPdf).

**Comment by harrydrippin** [comment]
Let me close this issue because it seems all things are done related with this issue.
