### ISSUE TITLE
Writing paper

### ISSUE THREAD

**Issue by learnitdeep** [EVlock/Blockgrid#2]
Yeah~

**Comment by learnitdeep** [comment]
formatting work

**Comment by harrydrippin** [comment]
> formatting finished : https://docs.google.com/document/d/1FVZVF-Sqhe8P-PsW8Ym1s7HhzZbWHKnR__kl-4sgCDQ/edit?usp=sharing

This issue should be closed and deleted because this link gives the privilege of editing to anyone.
